[FEAT] 작품 검색 API 구현 완료
Team-WSS/WSS-Server-AppJam pull request #10
Opened 2024-01-02 18:26 UTC by ChaeAg

## Related Issue

- feat/#9 -> dev
- close #9

## Key Changes

유저가 검색어를 입력해, 해당 검색어가 포함된 웹소설 작품 리스트를 반환하는 API를 구현했습니다.
프론트단의 무한스크롤 구현을 위해, 파라미터로 총 3가지 값을 받습니다.
- 직전 호출 마지막 작품의 ID - lastNovelId
- 한 번 호출로 가져올 데이터 수 - size
- 해당 워드를 포함한 작품을 조회하기 위한 검색어 - word

직전 호출 마지막 작품의 ID를 받는 이유는 무한스크롤을 **No-offset 방식**으로 구현했기 때문입니다.
#### No-offset 방식의 동작 흐름은 아래와 같습니다.
1. 첫 호출 시 마지막 작품이 없기 때문에 프론트에서 **lastNovelId를 최대한 큰 수로 지정**
2. lastNovelId 보다 **Id값이 작은** 작품들 중 **size개**만큼 **ID(내림차순)순**으로 데이터를 반환
3. 프론트에서 데이터를 받은 뒤 마지막 데이터 ID를 알아내어 다시 호출
   - API 파라미터의 **lastNovelId를 마지막 데이터의 ID로 지정** (size, word는 동일)
4. lastNovelId 보다 Id값이 작은 작품들 중 size개만큼 ID(내림차순)순으로 데이터를 반환
5. 만약 더 이상 불러올 데이터가 없다면 **빈 리스트를 반환**

`NovelRepository` 코드는 해당 설명을 참고해주세요!
```java
// lastNovelId보다 작은 novelId를 가지며, 제목에 특정 단어가 포함된 책들을 내림차순으로 정렬하여 가져온다.
// PageRequest 객체는 service단에서 size만큼 불러올 데이터의 개수를 지정해놓은 것
@Query(value = "SELECT n FROM Novel n WHERE n.novelId < ?1 AND n.novelTitle LIKE %?2% ORDER BY n.novelId DESC")
Slice<Novel> findByIdLessThanOrderByIdDesc(Long lastNovelId, PageRequest pageRequest, String word);
``` 

## To Reviewers

무한스크롤 API 구현은 처음이라 잘 구현을 한 건지 모르겠네요..!!
부족한 점이나 개선할 점이 있다면 말씀해주세요!!
바로 반영하도록 하겠습니다 :)

## References

https://kbwplace.tistory.com/178

2024-01-03 13:34 UTC, rinarina0429 requested changes
수고하셨습니다!

2024-01-03 13:34 UTC, rinarina0429 commented on src/main/java/com/wss/websoso/novel/NovelService.java
> +        PageRequest pageRequest = PageRequest.of(0, size);
0도 `public static final int DEFAULT_PAGE_NUMBER = 0;`이런식으로 상수로 바꾸는게 더 좋을까요? 아니면 그냥 이대로 0으로 가는게 나을까요?

2024-01-03 13:34 UTC, rinarina0429 commented on src/main/java/com/wss/websoso/novel/NovelService.java
> +        List<Novel> entityList = entitySlice.getContent();
이 부분 아래처럼 코드 더 간결해지게 리팩토링 할 수 있지 않을까요?

```
public List<Novel> getNovelsByWord(Long lastNovelId, int size, String word) {
    PageRequest pageRequest = PageRequest.of(DEFAULT_PAGE_NUMBER, size);
    Slice<Novel> entitySlice = novelRepository.findByIdLessThanOrderByIdDesc(lastNovelId, pageRequest, word);
    return entitySlice.getContent();
}
```

2024-01-03 16:09 UTC, ChaeAg commented on src/main/java/com/wss/websoso/novel/NovelService.java
> +        PageRequest pageRequest = PageRequest.of(0, size);
오! 문자열이나 숫자는 웬만하면 상수 처리 하는 것이 더 나은 것 같아요!!
상수 처리 하도록 할게요~~

2024-01-03 16:20 UTC, ChaeAg commented on src/main/java/com/wss/websoso/novel/NovelService.java
> +        List<Novel> entityList = entitySlice.getContent();
앗 이부분은 고민했던 부분이긴 한데 뭐가 좋은지 모르겠어서 그냥 뒀었거든요!
메서드가 불릴 때마다 entityList에 할당을 안해도 되니 나경님께서 제안해주신 코드가 더 좋은 것 같네요!
반영하겠습니다~!

2024-01-04 03:13 UTC, rinarina0429 approved these changes

2024-01-06 15:08 UTC, Kim-TaeUk approved these changes
LGTM! 고생하셨습니다 :)

2024-01-06 16:26 UTC, merged