[FEAT] 메모 작성 API(POST) 구현
Team-WSS/WSS-Server-AppJam pull request #19
Opened 2024-01-06 13:11 UTC by rinarina0429

## Related Issue

- feat/#18  -> dev
- close #18 

## Key Changes

## To Reviewers

## References

X

2024-01-06 15:58 UTC, Kim-TaeUk requested changes
yaml 빼주세요~~

2024-01-07 16:47 UTC, ChaeAg commented on src/main/java/com/wss/websoso/memo/MemoController.java
> +                        .body(Map.of("message", "memoContent의 최대 길이를 초과했습니다."));
이 때 `e.getMessage()` 로 에러 메세지를 출력해도 괜찮을 것 같아요!
아니면, 에러 메세지가 추후 변경되는 경우를 대비하여 상수로 정의하는 것도 괜찮을 것 같습니다!

2024-01-07 16:47 UTC, ChaeAg commented on src/main/java/com/wss/websoso/memo/MemoController.java
> +            @RequestBody MemoCreateRequest request,
혹시 해당 파라미터를 따로 DTO로 정의하신 이유가 있을까용?
단순히 `String memoContent`로 받는 방법도 있을 것 같아서요!!

2024-01-07 16:49 UTC, ChaeAg reviewed
야무지게 설계해주셨네요 👍👍 
수고하셨어요!!

2024-01-08 11:46 UTC, closed without merging