[FEAT] 유저 닉네임 변경 API 구현
Team-WSS/WSS-Server-AppJam pull request #25
Opened 2024-01-07 20:23 UTC by ChaeAg

## Related Issue

- feat/#24 -> dev
- close #24

## Key Changes

Request Body로 새로운 유저 닉네임을 받아, 현재 로그인한 유저의 닉네임을 변경하는 API를 구현했습니다.
기존 닉네임과 동일한 닉네임으로 변경 요청이 들어온 경우 에러를 발생시켜 에러 메세지를 클라이언트에게 전달하도록 설계했습니다.

## To Reviewers

X
## References

X

2024-01-10 22:18 UTC, Kim-TaeUk requested changes
userNickname 변경시 새로운 JWT 발급해야합니다.

2024-01-13 16:10 UTC, rinarina0429 approved these changes
수고하셨습니다!!

2024-01-13 16:10 UTC, rinarina0429 commented on src/main/java/com/wss/websoso/user/UserService.java
닉네임 10자 이상 작성한 것도 나중에 exception 따로 만들어 주는 것도 좋을 것 같습니다!

2024-01-13 19:49 UTC, ChaeAg commented
> userNickname 변경시 새로운 JWT 인증을 해야 합니다.

현재 클레임에 userNickname을 담지 않기 때문에 닉네임을 변경한다고 JWT 토큰에는 영향이 없습니다!

2024-01-13 19:52 UTC, Kim-TaeUk commented
> > userNickname 변경시 새로운 JWT 인증을 해야 합니다.
> 
> 현재 클레임에 userNickname을 담지 않기 때문에 닉네임을 변경한다고 JWT 토큰에는 영향이 없습니다!

확인했습니다.

2024-01-13 19:53 UTC, Kim-TaeUk commented on src/main/java/com/wss/websoso/user/User.java
> +    @Column(name = "user_nickname", length = 10, nullable = false)
요구사항에 맞게 size 명시적으로 지정해주었네요. 👍

2024-01-13 19:54 UTC, Kim-TaeUk commented on src/main/java/com/wss/websoso/user/UserNicknameUpdateResponse.java
> +        String userNickname,
userNickname을 또 내려주지 않아도 될 것 같습니다.

2024-01-13 19:56 UTC, Kim-TaeUk commented on src/main/java/com/wss/websoso/user/UserService.java
> +        if (newUserNickname.equals(user.getUserNickname())) {
null일 수 있어서 클라이언트에서도 validate하겠지만 서버에서도 하는게 좋을 것 같습니다.

2024-01-13 19:56 UTC, Kim-TaeUk requested changes
고생했습니다!

2024-01-13 20:17 UTC, Kim-TaeUk approved these changes

2024-01-13 20:17 UTC, Kim-TaeUk commented
머지합시다~~!

2024-01-13 20:46 UTC, merged