[FEAT] 요구사항 추가에 따른 도메인 수정 및 추가
Team-WSS/WSS-Server-AppJam pull request #44
Opened 2024-01-10 23:33 UTC by Kim-TaeUk

## Related Issue

- feat/#37 -> dev
- close #37 

## Key Changes

프로젝트 요구사항이 변경/추가되어 사용될 Avatar, User, UserAvatar, AvatarLine, GenreBadge 도메인 수정 및 구현했습니다.

2024-01-10 23:57 UTC, ChaeAg requested changes

2024-01-10 23:57 UTC, ChaeAg commented on src/main/java/com/wss/websoso/avatarLine/AvatarLine.java
> +    private Avatar avatar;
해당 연관관계는 Avatar가 삭제되면 해당 Avatar와 연결된 AvartarLine도 함께 삭제되어야 하기에, Avatar 엔티티에서도 AvatarLine 엔티티와의 양방향 매핑과 Cascade 속성을 주어야 할 것 같습니다.

2024-01-10 23:57 UTC, ChaeAg commented on src/main/java/com/wss/websoso/userAvatar/UserAvatar.java
해당 클래스도 User와 Avatar 엔티티의 자식엔티티이기 때문에 User 클래스와 Avartar 클래스에도 양방향 매핑과 Cascade 설정이 필요할 것 같습니다!

2024-01-10 23:59 UTC, Kim-TaeUk commented on src/main/java/com/wss/websoso/avatarLine/AvatarLine.java
> +    private Avatar avatar;
좋은 지적입니다. 감사합니다! 수정할게요.

2024-01-10 23:59 UTC, Kim-TaeUk commented on src/main/java/com/wss/websoso/userAvatar/UserAvatar.java
수정하겠습니다. 감사합니다.

2024-01-11 00:17 UTC, ChaeAg approved these changes
수고하셨습니다!! 👍

2024-01-11 00:17 UTC, merged